- name: Demo on Play Level Variables
  hosts: all
  vars:
    URL: play.example.com
  tasks:
     - name: Print URL
       ansible.builtin.debug:
        msg: URL - {{ URL }}
# In ansible variable will be accessed using double flower bracess {{ }}
#Ansible Supports double quotes and single quotes also , however quotes are not mandatory in all cases
#Quotes are mandatory if value start with a variable, meaning
# msg: {{ URL }} <- this requires quoting
# msg: URL - {{ URL }} <- this does not require quoting

- name: Load vars from a file
  hosts: all
  vars_files:
    - exvars.yml
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL - {{ URL }}
#vars_files doesn't supports task level, it is for play level only

- name: Demo on Task Level Variables
  hosts: all
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL - {{ URL }}
      vars:
       URL: tasks.example.com
#Only that task have that variable, other tasks cannot access it

- name: Variable from Role
  hosts: all
  vars:
     URL_PLAY: play.example.com
  roles:
    -sample