- name: Demo on loops
  hosts: localhost
  connection: local
  tasks:
    - name: Demo tasks for loops
      ansible.builtin.debug:
        msg: Fruit Name - {{ item }}
        loop:
          - apple
          - banana